/* tpk.c generated by valac 0.48.6, the Vala compiler
 * generated from tpk.vala, do not modify */

#include <glib.h>
#include <float.h>
#include <math.h>
#include <stdio.h>

gdouble f (gdouble t);
void _vala_main (void);

gdouble
f (gdouble t)
{
	gdouble result = 0.0;
	result = sqrt (fabs (t)) + (5 * pow (t, (gdouble) 3));
	return result;
}

void
_vala_main (void)
{
	gdouble a[11] = {0};
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp0_ = FALSE;
			_tmp0_ = TRUE;
			while (TRUE) {
				FILE* _tmp2_;
				if (!_tmp0_) {
					gint _tmp1_;
					_tmp1_ = i;
					i = _tmp1_ + 1;
				}
				_tmp0_ = FALSE;
				if (!(i < 11)) {
					break;
				}
				_tmp2_ = stdin;
				fscanf (_tmp2_, "%lf", &a[i]);
			}
		}
	}
	{
		gint i = 0;
		i = 11 - 1;
		{
			gboolean _tmp3_ = FALSE;
			_tmp3_ = TRUE;
			while (TRUE) {
				gdouble y = 0.0;
				gdouble _tmp5_;
				if (!_tmp3_) {
					gint _tmp4_;
					_tmp4_ = i;
					i = _tmp4_ - 1;
				}
				_tmp3_ = FALSE;
				if (!(i >= 0)) {
					break;
				}
				_tmp5_ = a[i];
				y = f (_tmp5_);
				if (y > ((gdouble) 400)) {
					g_print ("%d TOO LARGE\n", i);
				} else {
					g_print ("%d %.16g\n", i, y);
				}
			}
		}
	}
}

int
main (int argc,
      char ** argv)
{
	_vala_main ();
	return 0;
}

